name: Deploy

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 트리거
  pull_request:
    branches:
      - master  # master 브랜치에 PR이 열릴 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'  # Python 3.8.10 버전 설정

    - name: Install dependencies and run setup script
      run: |
        bash setup.sh

    - name: Deploy to Server
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        PROJECT_DIR: '~/dev/telegram-stock-info-noti-bot'
      run: |
        echo "Starting deployment..."
        rsync -avz --exclude 'venv' --exclude '.git' . $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
        ssh $DEPLOY_USER@$DEPLOY_SERVER << EOF
          echo "Connecting to server..."
          cd $DEPLOY_PATH
          git pull origin master
          source venv/bin/activate
          echo "Installing requirements..."
          pip install -r requirements.txt
          # setup.sh 스크립트 실행
          if [ -f setup.sh ]; then
            echo "Running setup.sh in $PROJECT_DIR..."
            bash setup.sh
          fi
          # 필요한 경우 추가 배포 명령어 실행
          echo "Deployment completed in $DEPLOY_PATH."
        EOF
